services:
  - type: web
    name: grocergo-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: "grocergo_secret_123"
      - key: MONGODB_URI
        value: "REQUIRED_PASTE_HERE"
      - key: SELLER_EMAIL
        value: "admin@grocergo.com"
      - key: SELLER_PASSWORD
        value: "admin123"
      - key: CLOUDINARY_CLOUD_NAME
        value: "REQUIRED_PASTE_HERE"
      - key: CLOUDINARY_API_KEY
        value: "REQUIRED_PASTE_HERE"
      - key: CLOUDINARY_API_SECRET
        value: "REQUIRED_PASTE_HERE"
      - key: STRIPE_SECRET_KEY
        value: "REQUIRED_PASTE_HERE"
      - key: STRIPE_WEBHOOK_SECRET
        value: "REQUIRED_PASTE_HERE"
